[package]
name = "multilayer_perceptron"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
opt-level = 3

[lib]
name = "mlp"
path = "src/mlp/mod.rs"

[dependencies]
rand = "0.8.5"

